language: python

cache: pip
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.5"

env:
  - VERSION=1.7 ES_URL="https://download.elasticsearch.org/elasticsearch/elasticsearch/" ES_DEB="elasticsearch-1.7.5.deb" REGISTRY_DATABASE_URL="postgres://localhost:5432/registry"
  - VERSION=5.1 ES_URL="https://artifacts.elastic.co/downloads/elasticsearch/" ES_DEB="elasticsearch-5.1.1.deb" REGISTRY_DATABASE_URL="postgres://localhost:5432/registry"

addons:
  postgresql: "9.5"
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - libgeos-c1
      - libxml2-dev
      - python-flake8
      - postgresql-9.5
      - postgresql-contrib-9.5

services:
  - postgresql

before_install: 
  # Remove error could not access file "$libdir/postgis-2.3": No such file or directory
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - pip install psycopg2
  - jdk_switcher use oraclejdk8
  - curl -O $ES_URL$ES_DEB
  - sudo dpkg -i --force-confnew $ES_DEB
  - wget https://www.dropbox.com/s/iepb2t39oz8v8oo/aggs-geoheatmap-5.1.1-SNAPSHOT.zip
  - if [ $VERSION == "5.1" ]; then sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///$(pwd)/aggs-geoheatmap-5.1.1-SNAPSHOT.zip; fi
  - sudo service elasticsearch restart

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py -q install

before_script:
  - psql -c 'create database registry;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d registry
  - python registry.py pycsw -c get_sysprof
  - python registry.py pycsw -c setup_db

script:
  - coverage run --source=registry setup.py test

after_script:
  - flake8 registry.py

after_success:
  - coveralls
